In [1]:
import pandas
import numpy

In [2]:
df = pandas.read_csv('Salary_Data.csv')

In [3]:
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [4]:
df.shape

(30, 2)

In [5]:
X = df.iloc[:, 0].values
y = df.iloc[:, 1].values

In [7]:
print(X.shape)
print(type(X))
print(len(X))
print(y.shape)
print(type(y))
print(len(y))

(30,)
<class 'numpy.ndarray'>
30
(30,)
<class 'numpy.ndarray'>
30


In [8]:
X = numpy.reshape(X, (-1, 1))
y = numpy.reshape(y, (-1, 1))

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

In [10]:
print(X_train.shape)
print(X_train)
print(y_train.shape)
print(y_train)

(20, 1)
[[ 2.9]
 [ 5.1]
 [ 3.2]
 [ 4.5]
 [ 8.2]
 [ 6.8]
 [ 1.3]
 [10.5]
 [ 3. ]
 [ 2.2]
 [ 5.9]
 [ 6. ]
 [ 3.7]
 [ 3.2]
 [ 9. ]
 [ 2. ]
 [ 1.1]
 [ 7.1]
 [ 4.9]
 [ 4. ]]
(20, 1)
[[ 56642.]
 [ 66029.]
 [ 64445.]
 [ 61111.]
 [113812.]
 [ 91738.]
 [ 46205.]
 [121872.]
 [ 60150.]
 [ 39891.]
 [ 81363.]
 [ 93940.]
 [ 57189.]
 [ 54445.]
 [105582.]
 [ 43525.]
 [ 39343.]
 [ 98273.]
 [ 67938.]
 [ 56957.]]


In [11]:
X_train = numpy.reshape(X_train, (-1, 1))
y_train = numpy.reshape(y_train, (-1, 1))

In [12]:
print(X_train.shape)
print(X_train)
print(y_train.shape)
print(y_train)

(20, 1)
[[ 2.9]
 [ 5.1]
 [ 3.2]
 [ 4.5]
 [ 8.2]
 [ 6.8]
 [ 1.3]
 [10.5]
 [ 3. ]
 [ 2.2]
 [ 5.9]
 [ 6. ]
 [ 3.7]
 [ 3.2]
 [ 9. ]
 [ 2. ]
 [ 1.1]
 [ 7.1]
 [ 4.9]
 [ 4. ]]
(20, 1)
[[ 56642.]
 [ 66029.]
 [ 64445.]
 [ 61111.]
 [113812.]
 [ 91738.]
 [ 46205.]
 [121872.]
 [ 60150.]
 [ 39891.]
 [ 81363.]
 [ 93940.]
 [ 57189.]
 [ 54445.]
 [105582.]
 [ 43525.]
 [ 39343.]
 [ 98273.]
 [ 67938.]
 [ 56957.]]


In [13]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
y_pred = regressor.predict([[1.8]])

In [22]:
y_pred

array([[43638.88864165]])

In [24]:
y_pred[0][0]

43638.88864165146